### ISSUE TITLE
Implement Dark Mode Feature

### ISSUE THREAD

**Issue by OmkarKirpan** [OmkarKirpan/GuessColors#14]
Create a dark mode option for the game interface, allowing users to switch to a darker color scheme for improved visibility in low-light environments.

**Comment by Muz4mmil** [comment]
Assign me this issue, i can integrate Dark mode easily with Plain CSS

**Comment by OmkarKirpan** [comment]
Assigned to you @Muz4mmil 😀
Thanks for picking this up 👍🏻

**Comment by Muz4mmil** [comment]
> Assigned to you @Muz4mmil 😀 Thanks for picking this up 👍🏻

No worries,
Can i also modify the UI to make it look slightly better??

**Comment by OmkarKirpan** [comment]
Yeah sure

**Comment by Muz4mmil** [comment]
> Assigned to you @Muz4mmil 😀 Thanks for picking this up 👍🏻

Done, kindly merge the PR
